CREATE FUNCTION GET_CODE_MIDDLE_NAME( AS_CD_TOP INT(11) , AS_CD_MIDDLE INT(11) )
RETURNS VARCHAR(32)
BEGIN
	DECLARE RTN_VAL VARCHAR(32);
	SELECT CD_MIDDLE_KR
	INTO RTN_VAL
	FROM MAS_CODE
	WHERE CD_TOP = AS_CD_TOP
	AND CD_MIDDLE = AS_CD_MIDDLE
	GROUP BY CD_TOP, CD_MIDDLE;
	RETURN RTN_VAL;
END;

CREATE FUNCTION GET_CODE_BOTTOM_NAME( AS_CD_TOP INT(11) , AS_CD_MIDDLE INT(11) , AS_CD_BOTTOM INT(11) )
RETURNS VARCHAR(32)
BEGIN
	DECLARE RTN_VAL VARCHAR(32);
	SELECT CD_BOTTOM_KR
	INTO RTN_VAL
	FROM MAS_CODE
	WHERE CD_TOP = AS_CD_TOP 
	AND CD_MIDDLE = AS_CD_MIDDLE
	AND CD_BOTTOM = AS_CD_BOTTOM;
	RETURN RTN_VAL;
END;


CREATE FUNCTION GET_USER_NAME(p_ACC_ID INT)
RETURNS varchar(64)
BEGIN
   DECLARE RTN_USER_NAME VARCHAR(64);
   SET RTN_USER_NAME = null;
   SELECT USER_NAME  INTO RTN_USER_NAME from MAS_ACCOUNT where ACC_ID = p_ACC_ID;   
	RETURN RTN_USER_NAME;
END;


CREATE FUNCTION GET_CD_STATE_NAME( AS_CD_STATE INT(11) )
RETURNS VARCHAR(32)
BEGIN
	DECLARE RTN_VAL VARCHAR(32);
	SELECT CASE 
			WHEN AS_CD_STATE = 1 THEN '등록' 
			WHEN AS_CD_STATE = 2 THEN '변경'
			WHEN AS_CD_STATE = 3 THEN '삭제'
			ELSE NULL
		END
	INTO RTN_VAL
	FROM DUAL;
	RETURN RTN_VAL;
END;


CREATE FUNCTION GET_AGT_NAME(p_AGT_ID INT)
RETURNS varchar(64)
BEGIN
   DECLARE RTN_AGT_NAME VARCHAR(64);
   SET RTN_AGT_NAME = null;
   SELECT AGT_NAME  INTO RTN_AGT_NAME from MAS_AGENT where AGT_ID = p_AGT_ID;   
   RETURN RTN_AGT_NAME;
END;